### ISSUE TITLE
Add /admin section

### ISSUE THREAD

**Issue by ZMYaro** [zmyaro/star-site#20]
Add /admin page with links to admin-exclusive functions.  Also move admin-exclusive URLs under /admin/\* to prevent confusion.

**Comment by dexw25** [comment]
Admin page should provide a way to create/retrieve/and revoke api keys

**Comment by ZMYaro** [comment]
Admin section created in https://github.com/RITSTARClub/star-site/pull/69.  Existing API key functions were moved there, but other API key functions were not added and should be part of a future release.
