### ISSUE TITLE
Move rank-related functions to a separate Python file

### ISSUE THREAD

**Issue by ZMYaro** [zmyaro/star-site#35]
Move rank-related function definitions out of `models.py` and into a separate Python file.

**Comment by dexw25** [comment]
Does this just involve rank display functions, or also rank calculation? I'm poking through the code, and those functions are currently part of the member class, and would require more than just moving to make them work in another file

**Comment by ZMYaro** [comment]
IIRC, this was mostly about making `models.py` more readable (and having an obvious place to look if someone wanted to understand the rank calculator), and the idea was to move the rank constants dictionary and all rank calculation functions to a separate class.  The functions would each still take a `Member` object and a semester float; the `Member` would just no longer be `self`.

Having those functions not be part of `Member` might also remind future devs that rank calculation has a additional cost on top of retrieving the member from the datastore.

**Comment by ZMYaro** [comment]
Additionally, giving the constants dictionary and calculator function some attention might reveal ways we can improve them.

**Comment by dexw25** [comment]
I guess for future expansion, this makes sense. Also re-emphasizes that
rank values are not stored, but calculated on demand. I can get this done.
