### ISSUE TITLE
Move date formatting functions to a separate Python file

### ISSUE THREAD

**Issue by ZMYaro** [zmyaro/star-site#36]
Move date formatting function definitions out of `models.py` and into a separate Python file.

**Comment by dexw25** [comment]
Date formatting functions are currently used to populate certain values of the mission class, should this be done elsewhere? (Where formatted dates are needed) I just want to be sure how much refactoring is needed

**Comment by ZMYaro** [comment]
IIRC, the idea was to have a functions for formatting single date objects and date ranges (two date objects) and each return a string formatted as a short (2012-12-21) or long (December 21, 2012) date, with or without a time attached.

 If you do not think it is worth doing at this time, we can remove these changes from r5 and wait until they become necessary.

**Comment by dexw25** [comment]
I guess that specific function would be useful to centralize in another
file (formatting date ranges), probably justifies the whole task. I should
be able to get that done without too much trouble.
