### ISSUE TITLE
Missions page returns Error 500 with empty date fields

### ISSUE THREAD

**Issue by dexw25** [zmyaro/star-site#48]
Steps to reproduce: create a new mission and leave the date fields blank

Recommended solution: require data in that field, don't error out

**Comment by ZMYaro** [comment]
Note to self: the `<input>`s do not have `required` attributes; they should.  Double-check that all required inputs have `required` attributes.

**Comment by ZMYaro** [comment]
This was sort of forgotten.  Updating to R12.

**Comment by ZMYaro** [comment]
This no longer produces an error for me; the missions properly go to the hidden/unscheduled missions list.  @derekw023: are you still able to reproduce the error?  Else, I will close this and assume it was fixed.

**Comment by dexw25** [comment]
Yeah this was an old one, probably got fixed by some other change. I doubt I'd be able to reproduce
