### ISSUE TITLE
Social icons occasionally misalign

### ISSUE THREAD

**Issue by GregoryGhiroli** [zmyaro/star-site#97]
![problem](https://user-images.githubusercontent.com/31124595/39022165-3d32a7d6-4402-11e8-9c5c-8c85134fc0ec.PNG)

The error is because the a tag for the email is transparent to the background but still there in the foot.html.
Because of the length and not being given a hidden overflow the mail icon is placed lower making it off of the inline-block with the other icons. This is created on a windows 10 laptop hp envy, using google chrome. When zoomed in or change of window size the icon is suddenly no longer inline because of the a tag description of the email.

**Comment by ZMYaro** [comment]
Note to self: make social icons have `white-space: nowrap; overflow: hidden;`.
